set(ITKDeformableMesh_LOADED 1)
set(ITKDeformableMesh_ENABLE_SHARED "0")
set(ITKDeformableMesh_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PUBLIC_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_TRANSITIVE_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_PRIVATE_DEPENDS "")
set(ITKDeformableMesh_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh")
set(ITKDeformableMesh_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKDeformableMesh_LIBRARY_DIRS "")
set(ITKDeformableMesh_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKDeformableMesh_TARGETS_FILE "")

