set(ITKFiniteDifference_LOADED 1)
set(ITKFiniteDifference_ENABLE_SHARED "0")
set(ITKFiniteDifference_DEPENDS "ITKCommon")
set(ITKFiniteDifference_PUBLIC_DEPENDS "")
set(ITKFiniteDifference_TRANSITIVE_DEPENDS "ITKCommon")
set(ITKFiniteDifference_PRIVATE_DEPENDS "")
set(ITKFiniteDifference_LIBRARIES "ITKCommon")
set(ITKFiniteDifference_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKFiniteDifference_LIBRARY_DIRS "")
set(ITKFiniteDifference_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKFiniteDifference_TARGETS_FILE "")

