set(ITKGPUImageFilterBase_LOADED 1)
set(ITKGPUImageFilterBase_ENABLE_SHARED "0")
set(ITKGPUImageFilterBase_DEPENDS "ITKCommon;ITKGPUCommon;ITKImageFilterBase")
set(ITKGPUImageFilterBase_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUImageFilterBase_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKImageFilterBase")
set(ITKGPUImageFilterBase_PRIVATE_DEPENDS "")
set(ITKGPUImageFilterBase_LIBRARIES "ITKCommon")
set(ITKGPUImageFilterBase_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKGPUImageFilterBase_LIBRARY_DIRS "")
set(ITKGPUImageFilterBase_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUImageFilterBase_TARGETS_FILE "")

