set(ITKGPUThresholding_LOADED 1)
set(ITKGPUThresholding_ENABLE_SHARED "0")
set(ITKGPUThresholding_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUThresholding_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKThresholding")
set(ITKGPUThresholding_PRIVATE_DEPENDS "")
set(ITKGPUThresholding_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKGPUThresholding_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKGPUThresholding_LIBRARY_DIRS "")
set(ITKGPUThresholding_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUThresholding_TARGETS_FILE "")

