set(ITKIOSpatialObjects_LOADED 1)
set(ITKIOSpatialObjects_ENABLE_SHARED "0")
set(ITKIOSpatialObjects_DEPENDS "ITKIOXML;ITKMesh;ITKSpatialObjects")
set(ITKIOSpatialObjects_PUBLIC_DEPENDS "")
set(ITKIOSpatialObjects_TRANSITIVE_DEPENDS "")
set(ITKIOSpatialObjects_PRIVATE_DEPENDS "ITKIOXML;ITKMesh;ITKSpatialObjects")
set(ITKIOSpatialObjects_LIBRARIES "ITKIOSpatialObjects")
set(ITKIOSpatialObjects_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKIOSpatialObjects_LIBRARY_DIRS "")
set(ITKIOSpatialObjects_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKIOSpatialObjects_TARGETS_FILE "")

