set(ITKLabelMap_LOADED 1)
set(ITKLabelMap_ENABLE_SHARED "1")
set(ITKLabelMap_DEPENDS "ITKStatistics;ITKTransform")
set(ITKLabelMap_PUBLIC_DEPENDS "")
set(ITKLabelMap_TRANSITIVE_DEPENDS "ITKTransform")
set(ITKLabelMap_PRIVATE_DEPENDS "ITKStatistics")
set(ITKLabelMap_LIBRARIES "ITKLabelMap")
set(ITKLabelMap_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKLabelMap_LIBRARY_DIRS "")
set(ITKLabelMap_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKLabelMap_TARGETS_FILE "")

