set(ITKMarkovRandomFieldsClassifiers_LOADED 1)
set(ITKMarkovRandomFieldsClassifiers_ENABLE_SHARED "0")
set(ITKMarkovRandomFieldsClassifiers_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_PUBLIC_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_TRANSITIVE_DEPENDS "ITKClassifiers;ITKStatistics")
set(ITKMarkovRandomFieldsClassifiers_PRIVATE_DEPENDS "")
set(ITKMarkovRandomFieldsClassifiers_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKMarkovRandomFieldsClassifiers_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKMarkovRandomFieldsClassifiers_LIBRARY_DIRS "")
set(ITKMarkovRandomFieldsClassifiers_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKMarkovRandomFieldsClassifiers_TARGETS_FILE "")

