set(ITKNeuralNetworks_LOADED 1)
set(ITKNeuralNetworks_ENABLE_SHARED "0")
set(ITKNeuralNetworks_DEPENDS "ITKStatistics")
set(ITKNeuralNetworks_PUBLIC_DEPENDS "ITKStatistics")
set(ITKNeuralNetworks_TRANSITIVE_DEPENDS "ITKStatistics")
set(ITKNeuralNetworks_PRIVATE_DEPENDS "")
set(ITKNeuralNetworks_LIBRARIES "ITKStatistics")
set(ITKNeuralNetworks_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKNeuralNetworks_LIBRARY_DIRS "")
set(ITKNeuralNetworks_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKNeuralNetworks_TARGETS_FILE "")

