set(ITKPDEDeformableRegistration_LOADED 1)
set(ITKPDEDeformableRegistration_ENABLE_SHARED "0")
set(ITKPDEDeformableRegistration_DEPENDS "ITKFiniteDifference;ITKRegistrationCommon")
set(ITKPDEDeformableRegistration_PUBLIC_DEPENDS "ITKFiniteDifference;ITKRegistrationCommon")
set(ITKPDEDeformableRegistration_TRANSITIVE_DEPENDS "ITKFiniteDifference;ITKRegistrationCommon")
set(ITKPDEDeformableRegistration_PRIVATE_DEPENDS "")
set(ITKPDEDeformableRegistration_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers")
set(ITKPDEDeformableRegistration_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKPDEDeformableRegistration_LIBRARY_DIRS "")
set(ITKPDEDeformableRegistration_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKPDEDeformableRegistration_TARGETS_FILE "")

