set(ITKQuadEdgeMeshFiltering_LOADED 1)
set(ITKQuadEdgeMeshFiltering_ENABLE_SHARED "0")
set(ITKQuadEdgeMeshFiltering_DEPENDS "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_PUBLIC_DEPENDS "ITKMesh")
set(ITKQuadEdgeMeshFiltering_TRANSITIVE_DEPENDS "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_PRIVATE_DEPENDS "")
set(ITKQuadEdgeMeshFiltering_LIBRARIES "ITKMesh;ITKQuadEdgeMesh")
set(ITKQuadEdgeMeshFiltering_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKQuadEdgeMeshFiltering_LIBRARY_DIRS "")
set(ITKQuadEdgeMeshFiltering_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKQuadEdgeMeshFiltering_TARGETS_FILE "")

