set(ITKRegistrationMethodsv4_LOADED 1)
set(ITKRegistrationMethodsv4_ENABLE_SHARED "0")
set(ITKRegistrationMethodsv4_DEPENDS "ITKMetricsv4;ITKOptimizersv4")
set(ITKRegistrationMethodsv4_PUBLIC_DEPENDS "ITKMetricsv4;ITKOptimizersv4")
set(ITKRegistrationMethodsv4_TRANSITIVE_DEPENDS "ITKMetricsv4;ITKOptimizersv4")
set(ITKRegistrationMethodsv4_PRIVATE_DEPENDS "")
set(ITKRegistrationMethodsv4_LIBRARIES "ITKCommon;ITKOptimizersv4;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers")
set(ITKRegistrationMethodsv4_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKRegistrationMethodsv4_LIBRARY_DIRS "")
set(ITKRegistrationMethodsv4_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKRegistrationMethodsv4_TARGETS_FILE "")

