#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "itkdouble-conversion" for configuration "Release"
set_property(TARGET itkdouble-conversion APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkdouble-conversion PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkdouble-conversion-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkdouble-conversion )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkdouble-conversion "${_IMPORT_PREFIX}/lib/itkdouble-conversion-4.12.lib" )

# Import target "itksys" for configuration "Release"
set_property(TARGET itksys APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itksys PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32;Psapi"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itksys-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itksys )
list(APPEND _IMPORT_CHECK_FILES_FOR_itksys "${_IMPORT_PREFIX}/lib/itksys-4.12.lib" )

# Import target "itkvcl" for configuration "Release"
set_property(TARGET itkvcl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvcl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkvcl-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkvcl )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkvcl "${_IMPORT_PREFIX}/lib/itkvcl-4.12.lib" )

# Import target "itknetlib" for configuration "Release"
set_property(TARGET itknetlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itknetlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itknetlib-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itknetlib )
list(APPEND _IMPORT_CHECK_FILES_FOR_itknetlib "${_IMPORT_PREFIX}/lib/itknetlib-4.12.lib" )

# Import target "itkv3p_netlib" for configuration "Release"
set_property(TARGET itkv3p_netlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkv3p_netlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkv3p_netlib-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkv3p_netlib )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkv3p_netlib "${_IMPORT_PREFIX}/lib/itkv3p_netlib-4.12.lib" )

# Import target "itkvnl" for configuration "Release"
set_property(TARGET itkvnl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvnl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkvcl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkvnl-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkvnl )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkvnl "${_IMPORT_PREFIX}/lib/itkvnl-4.12.lib" )

# Import target "itkvnl_algo" for configuration "Release"
set_property(TARGET itkvnl_algo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkvnl_algo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itknetlib;itkv3p_netlib;itkvnl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkvnl_algo-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkvnl_algo )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkvnl_algo "${_IMPORT_PREFIX}/lib/itkvnl_algo-4.12.lib" )

# Import target "itktestlib" for configuration "Release"
set_property(TARGET itktestlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itktestlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkvcl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itktestlib-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itktestlib )
list(APPEND _IMPORT_CHECK_FILES_FOR_itktestlib "${_IMPORT_PREFIX}/lib/itktestlib-4.12.lib" )

# Import target "ITKVNLInstantiation" for configuration "Release"
set_property(TARGET ITKVNLInstantiation APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVNLInstantiation PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl;itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKVNLInstantiation-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKVNLInstantiation )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKVNLInstantiation "${_IMPORT_PREFIX}/lib/ITKVNLInstantiation-4.12.lib" )

# Import target "ITKCommon" for configuration "Release"
set_property(TARGET ITKCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKCommon PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKCommon-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itksys;ITKVNLInstantiation"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKCommon-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKCommon )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKCommon "${_IMPORT_PREFIX}/lib/ITKCommon-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKCommon-4.12.dll" )

# Import target "itkNetlibSlatec" for configuration "Release"
set_property(TARGET itkNetlibSlatec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkNetlibSlatec PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkv3p_netlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkNetlibSlatec-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkNetlibSlatec )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkNetlibSlatec "${_IMPORT_PREFIX}/lib/itkNetlibSlatec-4.12.lib" )

# Import target "ITKStatistics" for configuration "Release"
set_property(TARGET ITKStatistics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKStatistics PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKStatistics-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;itkNetlibSlatec"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKStatistics-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKStatistics )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKStatistics "${_IMPORT_PREFIX}/lib/ITKStatistics-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKStatistics-4.12.dll" )

# Import target "ITKTransform" for configuration "Release"
set_property(TARGET ITKTransform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKTransform PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKTransform-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKTransform-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKTransform )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKTransform "${_IMPORT_PREFIX}/lib/ITKTransform-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKTransform-4.12.dll" )

# Import target "ITKLabelMap" for configuration "Release"
set_property(TARGET ITKLabelMap APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKLabelMap PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKLabelMap-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKStatistics"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKLabelMap-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKLabelMap )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKLabelMap "${_IMPORT_PREFIX}/lib/ITKLabelMap-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKLabelMap-4.12.dll" )

# Import target "ITKMesh" for configuration "Release"
set_property(TARGET ITKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKMesh-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKTransform"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKMesh-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKMesh "${_IMPORT_PREFIX}/lib/ITKMesh-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKMesh-4.12.dll" )

# Import target "itkzlib" for configuration "Release"
set_property(TARGET itkzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkzlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkzlib-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkzlib )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkzlib "${_IMPORT_PREFIX}/lib/itkzlib-4.12.lib" )

# Import target "ITKMetaIO" for configuration "Release"
set_property(TARGET ITKMetaIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKMetaIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib;comctl32;wsock32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKMetaIO-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKMetaIO )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKMetaIO "${_IMPORT_PREFIX}/lib/ITKMetaIO-4.12.lib" )

# Import target "ITKSpatialObjects" for configuration "Release"
set_property(TARGET ITKSpatialObjects APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKSpatialObjects PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKTransform;ITKCommon;ITKMesh"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKSpatialObjects-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKSpatialObjects )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKSpatialObjects "${_IMPORT_PREFIX}/lib/ITKSpatialObjects-4.12.lib" )

# Import target "ITKPath" for configuration "Release"
set_property(TARGET ITKPath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKPath PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKPath-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKPath )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKPath "${_IMPORT_PREFIX}/lib/ITKPath-4.12.lib" )

# Import target "ITKQuadEdgeMesh" for configuration "Release"
set_property(TARGET ITKQuadEdgeMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKQuadEdgeMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKQuadEdgeMesh-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKMesh"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKQuadEdgeMesh-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKQuadEdgeMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKQuadEdgeMesh "${_IMPORT_PREFIX}/lib/ITKQuadEdgeMesh-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKQuadEdgeMesh-4.12.dll" )

# Import target "ITKIOImageBase" for configuration "Release"
set_property(TARGET ITKIOImageBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOImageBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOImageBase-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOImageBase-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOImageBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOImageBase "${_IMPORT_PREFIX}/lib/ITKIOImageBase-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOImageBase-4.12.dll" )

# Import target "ITKOptimizers" for configuration "Release"
set_property(TARGET ITKOptimizers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKOptimizers PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKOptimizers-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKStatistics"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKOptimizers-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKOptimizers )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKOptimizers "${_IMPORT_PREFIX}/lib/ITKOptimizers-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKOptimizers-4.12.dll" )

# Import target "ITKPolynomials" for configuration "Release"
set_property(TARGET ITKPolynomials APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKPolynomials PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKPolynomials-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKPolynomials-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKPolynomials )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKPolynomials "${_IMPORT_PREFIX}/lib/ITKPolynomials-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKPolynomials-4.12.dll" )

# Import target "ITKBiasCorrection" for configuration "Release"
set_property(TARGET ITKBiasCorrection APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKBiasCorrection PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKBiasCorrection-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKBiasCorrection-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKBiasCorrection )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKBiasCorrection "${_IMPORT_PREFIX}/lib/ITKBiasCorrection-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKBiasCorrection-4.12.dll" )

# Import target "ITKBioCell" for configuration "Release"
set_property(TARGET ITKBioCell APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKBioCell PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKBioCell-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKMesh"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKBioCell-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKBioCell )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKBioCell "${_IMPORT_PREFIX}/lib/ITKBioCell-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKBioCell-4.12.dll" )

# Import target "ITKDICOMParser" for configuration "Release"
set_property(TARGET ITKDICOMParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKDICOMParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKDICOMParser-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKDICOMParser )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKDICOMParser "${_IMPORT_PREFIX}/lib/ITKDICOMParser-4.12.lib" )

# Import target "ITKEXPAT" for configuration "Release"
set_property(TARGET ITKEXPAT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKEXPAT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKEXPAT-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKEXPAT )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKEXPAT "${_IMPORT_PREFIX}/lib/ITKEXPAT-4.12.lib" )

# Import target "ITKIOXML" for configuration "Release"
set_property(TARGET ITKIOXML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOXML PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOXML-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOXML-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOXML )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOXML "${_IMPORT_PREFIX}/lib/ITKIOXML-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOXML-4.12.dll" )

# Import target "ITKIOSpatialObjects" for configuration "Release"
set_property(TARGET ITKIOSpatialObjects APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOSpatialObjects PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOXML;ITKMesh;ITKSpatialObjects"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOSpatialObjects-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOSpatialObjects )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOSpatialObjects "${_IMPORT_PREFIX}/lib/ITKIOSpatialObjects-4.12.lib" )

# Import target "ITKFEM" for configuration "Release"
set_property(TARGET ITKFEM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKFEM PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKFEM-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;ITKStatistics;ITKTransform;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKOptimizers;ITKMetaIO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKFEM-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKFEM )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKFEM "${_IMPORT_PREFIX}/lib/ITKFEM-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKFEM-4.12.dll" )

# Import target "gdcmCommon" for configuration "Release"
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32;crypt32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmCommon-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmCommon )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmCommon "${_IMPORT_PREFIX}/lib/itkgdcmCommon-4.12.lib" )

# Import target "gdcmDICT" for configuration "Release"
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmDICT-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmDICT )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmDICT "${_IMPORT_PREFIX}/lib/itkgdcmDICT-4.12.lib" )

# Import target "gdcmDSED" for configuration "Release"
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmCommon;itkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmDSED-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmDSED )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmDSED "${_IMPORT_PREFIX}/lib/itkgdcmDSED-4.12.lib" )

# Import target "gdcmIOD" for configuration "Release"
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmDSED;gdcmCommon;ITKEXPAT"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmIOD-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmIOD )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmIOD "${_IMPORT_PREFIX}/lib/itkgdcmIOD-4.12.lib" )

# Import target "gdcmMSFF" for configuration "Release"
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmIOD;gdcmDSED;gdcmDICT;gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjpeg;gdcmcharls;rpcrt4"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmMSFF-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmMSFF )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmMSFF "${_IMPORT_PREFIX}/lib/itkgdcmMSFF-4.12.lib" )

# Import target "gdcmMEXD" for configuration "Release"
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;gdcmsocketxx;ws2_32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmMEXD-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmMEXD )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmMEXD "${_IMPORT_PREFIX}/lib/itkgdcmMEXD-4.12.lib" )

# Import target "gdcmjpeg8" for configuration "Release"
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmjpeg8-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmjpeg8 )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmjpeg8 "${_IMPORT_PREFIX}/lib/itkgdcmjpeg8-4.12.lib" )

# Import target "gdcmjpeg12" for configuration "Release"
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmjpeg12-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmjpeg12 )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmjpeg12 "${_IMPORT_PREFIX}/lib/itkgdcmjpeg12-4.12.lib" )

# Import target "gdcmjpeg16" for configuration "Release"
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmjpeg16-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmjpeg16 )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmjpeg16 "${_IMPORT_PREFIX}/lib/itkgdcmjpeg16-4.12.lib" )

# Import target "gdcmopenjpeg" for configuration "Release"
set_property(TARGET gdcmopenjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmopenjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmopenjpeg-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmopenjpeg )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmopenjpeg "${_IMPORT_PREFIX}/lib/itkgdcmopenjpeg-4.12.lib" )

# Import target "gdcmcharls" for configuration "Release"
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmcharls-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmcharls )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmcharls "${_IMPORT_PREFIX}/lib/itkgdcmcharls-4.12.lib" )

# Import target "gdcmsocketxx" for configuration "Release"
set_property(TARGET gdcmsocketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gdcmsocketxx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32.lib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkgdcmsocketxx-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS gdcmsocketxx )
list(APPEND _IMPORT_CHECK_FILES_FOR_gdcmsocketxx "${_IMPORT_PREFIX}/lib/itkgdcmsocketxx-4.12.lib" )

# Import target "ITKznz" for configuration "Release"
set_property(TARGET ITKznz APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKznz PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKznz-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKznz )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKznz "${_IMPORT_PREFIX}/lib/ITKznz-4.12.lib" )

# Import target "ITKniftiio" for configuration "Release"
set_property(TARGET ITKniftiio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKniftiio PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKznz"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKniftiio-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKniftiio )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKniftiio "${_IMPORT_PREFIX}/lib/ITKniftiio-4.12.lib" )

# Import target "ITKgiftiio" for configuration "Release"
set_property(TARGET ITKgiftiio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKgiftiio PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKEXPAT;ITKznz;ITKniftiio"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKgiftiio-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKgiftiio )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKgiftiio "${_IMPORT_PREFIX}/lib/ITKgiftiio-4.12.lib" )

# Import target "hdf5-static" for configuration "Release"
set_property(TARGET hdf5-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libitkhdf5.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS hdf5-static )
list(APPEND _IMPORT_CHECK_FILES_FOR_hdf5-static "${_IMPORT_PREFIX}/lib/libitkhdf5.lib" )

# Import target "hdf5_cpp-static" for configuration "Release"
set_property(TARGET hdf5_cpp-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5_cpp-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5-static"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libitkhdf5_cpp.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS hdf5_cpp-static )
list(APPEND _IMPORT_CHECK_FILES_FOR_hdf5_cpp-static "${_IMPORT_PREFIX}/lib/libitkhdf5_cpp.lib" )

# Import target "ITKIOBMP" for configuration "Release"
set_property(TARGET ITKIOBMP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOBMP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOBMP-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOBMP-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOBMP )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOBMP "${_IMPORT_PREFIX}/lib/ITKIOBMP-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOBMP-4.12.dll" )

# Import target "ITKIOBioRad" for configuration "Release"
set_property(TARGET ITKIOBioRad APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOBioRad PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOBioRad-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOBioRad-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOBioRad )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOBioRad "${_IMPORT_PREFIX}/lib/ITKIOBioRad-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOBioRad-4.12.dll" )

# Import target "ITKIOCSV" for configuration "Release"
set_property(TARGET ITKIOCSV APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOCSV PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOCSV-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOCSV-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOCSV )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOCSV "${_IMPORT_PREFIX}/lib/ITKIOCSV-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOCSV-4.12.dll" )

# Import target "ITKIOGDCM" for configuration "Release"
set_property(TARGET ITKIOGDCM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGDCM PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOGDCM-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "gdcmDICT;gdcmMSFF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOGDCM-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOGDCM )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOGDCM "${_IMPORT_PREFIX}/lib/ITKIOGDCM-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOGDCM-4.12.dll" )

# Import target "ITKIOIPL" for configuration "Release"
set_property(TARGET ITKIOIPL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOIPL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOIPL-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOIPL-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOIPL )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOIPL "${_IMPORT_PREFIX}/lib/ITKIOIPL-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOIPL-4.12.dll" )

# Import target "ITKIOGE" for configuration "Release"
set_property(TARGET ITKIOGE APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGE PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOGE-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOIPL;ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOGE-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOGE )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOGE "${_IMPORT_PREFIX}/lib/ITKIOGE-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOGE-4.12.dll" )

# Import target "ITKIOGIPL" for configuration "Release"
set_property(TARGET ITKIOGIPL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOGIPL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOGIPL-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOGIPL-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOGIPL )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOGIPL "${_IMPORT_PREFIX}/lib/ITKIOGIPL-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOGIPL-4.12.dll" )

# Import target "ITKIOHDF5" for configuration "Release"
set_property(TARGET ITKIOHDF5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOHDF5 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOHDF5-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOHDF5-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOHDF5 )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOHDF5 "${_IMPORT_PREFIX}/lib/ITKIOHDF5-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOHDF5-4.12.dll" )

# Import target "itkjpeg" for configuration "Release"
set_property(TARGET itkjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkjpeg-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkjpeg )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkjpeg "${_IMPORT_PREFIX}/lib/itkjpeg-4.12.lib" )

# Import target "ITKIOJPEG" for configuration "Release"
set_property(TARGET ITKIOJPEG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOJPEG PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOJPEG-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOJPEG-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOJPEG )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOJPEG "${_IMPORT_PREFIX}/lib/ITKIOJPEG-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOJPEG-4.12.dll" )

# Import target "itktiff" for configuration "Release"
set_property(TARGET itktiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itktiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib;itkjpeg"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itktiff-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itktiff )
list(APPEND _IMPORT_CHECK_FILES_FOR_itktiff "${_IMPORT_PREFIX}/lib/itktiff-4.12.lib" )

# Import target "ITKIOTIFF" for configuration "Release"
set_property(TARGET ITKIOTIFF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTIFF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOTIFF-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOTIFF-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOTIFF )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOTIFF "${_IMPORT_PREFIX}/lib/ITKIOTIFF-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOTIFF-4.12.dll" )

# Import target "ITKIOLSM" for configuration "Release"
set_property(TARGET ITKIOLSM APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOLSM PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOLSM-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase;ITKIOTIFF"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOLSM-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOLSM )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOLSM "${_IMPORT_PREFIX}/lib/ITKIOLSM-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOLSM-4.12.dll" )

# Import target "ITKIOMRC" for configuration "Release"
set_property(TARGET ITKIOMRC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMRC PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOMRC-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOMRC-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOMRC )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOMRC "${_IMPORT_PREFIX}/lib/ITKIOMRC-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOMRC-4.12.dll" )

# Import target "ITKIOMesh" for configuration "Release"
set_property(TARGET ITKIOMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOMesh-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOMesh-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOMesh "${_IMPORT_PREFIX}/lib/ITKIOMesh-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOMesh-4.12.dll" )

# Import target "ITKIOMeta" for configuration "Release"
set_property(TARGET ITKIOMeta APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOMeta PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOMeta-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKMetaIO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOMeta-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOMeta )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOMeta "${_IMPORT_PREFIX}/lib/ITKIOMeta-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOMeta-4.12.dll" )

# Import target "ITKIONIFTI" for configuration "Release"
set_property(TARGET ITKIONIFTI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIONIFTI PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIONIFTI-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase;ITKTransform"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKznz;ITKniftiio"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIONIFTI-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIONIFTI )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIONIFTI "${_IMPORT_PREFIX}/lib/ITKIONIFTI-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIONIFTI-4.12.dll" )

# Import target "ITKNrrdIO" for configuration "Release"
set_property(TARGET ITKNrrdIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKNrrdIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKNrrdIO-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKNrrdIO )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKNrrdIO "${_IMPORT_PREFIX}/lib/ITKNrrdIO-4.12.lib" )

# Import target "ITKIONRRD" for configuration "Release"
set_property(TARGET ITKIONRRD APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIONRRD PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIONRRD-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIONRRD-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIONRRD )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIONRRD "${_IMPORT_PREFIX}/lib/ITKIONRRD-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIONRRD-4.12.dll" )

# Import target "itkpng" for configuration "Release"
set_property(TARGET itkpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "itkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/itkpng-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkpng )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkpng "${_IMPORT_PREFIX}/lib/itkpng-4.12.lib" )

# Import target "ITKIOPNG" for configuration "Release"
set_property(TARGET ITKIOPNG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOPNG PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOPNG-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOPNG-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOPNG )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOPNG "${_IMPORT_PREFIX}/lib/ITKIOPNG-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOPNG-4.12.dll" )

# Import target "ITKIOSiemens" for configuration "Release"
set_property(TARGET ITKIOSiemens APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOSiemens PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOSiemens-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOIPL;ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOSiemens-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOSiemens )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOSiemens "${_IMPORT_PREFIX}/lib/ITKIOSiemens-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOSiemens-4.12.dll" )

# Import target "ITKIOStimulate" for configuration "Release"
set_property(TARGET ITKIOStimulate APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOStimulate PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOStimulate-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOStimulate-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOStimulate )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOStimulate "${_IMPORT_PREFIX}/lib/ITKIOStimulate-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOStimulate-4.12.dll" )

# Import target "ITKTransformFactory" for configuration "Release"
set_property(TARGET ITKTransformFactory APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKTransformFactory PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;ITKTransform"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKTransformFactory-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKTransformFactory )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKTransformFactory "${_IMPORT_PREFIX}/lib/ITKTransformFactory-4.12.lib" )

# Import target "ITKIOTransformBase" for configuration "Release"
set_property(TARGET ITKIOTransformBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOTransformBase-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;ITKTransform;ITKTransformFactory"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOTransformBase-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOTransformBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOTransformBase "${_IMPORT_PREFIX}/lib/ITKIOTransformBase-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOTransformBase-4.12.dll" )

# Import target "ITKIOTransformHDF5" for configuration "Release"
set_property(TARGET ITKIOTransformHDF5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformHDF5 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOTransformHDF5-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOTransformBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOTransformHDF5-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOTransformHDF5 )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOTransformHDF5 "${_IMPORT_PREFIX}/lib/ITKIOTransformHDF5-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOTransformHDF5-4.12.dll" )

# Import target "ITKIOTransformInsightLegacy" for configuration "Release"
set_property(TARGET ITKIOTransformInsightLegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformInsightLegacy PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOTransformInsightLegacy-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOTransformBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOTransformInsightLegacy-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOTransformInsightLegacy )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOTransformInsightLegacy "${_IMPORT_PREFIX}/lib/ITKIOTransformInsightLegacy-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOTransformInsightLegacy-4.12.dll" )

# Import target "ITKIOTransformMatlab" for configuration "Release"
set_property(TARGET ITKIOTransformMatlab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOTransformMatlab PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOTransformMatlab-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOTransformBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOTransformMatlab-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOTransformMatlab )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOTransformMatlab "${_IMPORT_PREFIX}/lib/ITKIOTransformMatlab-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOTransformMatlab-4.12.dll" )

# Import target "ITKIOVTK" for configuration "Release"
set_property(TARGET ITKIOVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKIOVTK PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKIOVTK-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKIOImageBase"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKIOVTK-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKIOVTK )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKIOVTK "${_IMPORT_PREFIX}/lib/ITKIOVTK-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKIOVTK-4.12.dll" )

# Import target "ITKKLMRegionGrowing" for configuration "Release"
set_property(TARGET ITKKLMRegionGrowing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKKLMRegionGrowing PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKKLMRegionGrowing-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKKLMRegionGrowing-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKKLMRegionGrowing )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKKLMRegionGrowing "${_IMPORT_PREFIX}/lib/ITKKLMRegionGrowing-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKKLMRegionGrowing-4.12.dll" )

# Import target "ITKOptimizersv4" for configuration "Release"
set_property(TARGET ITKOptimizersv4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKOptimizersv4 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKOptimizersv4-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKOptimizers"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKOptimizersv4-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKOptimizersv4 )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKOptimizersv4 "${_IMPORT_PREFIX}/lib/ITKOptimizersv4-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKOptimizersv4-4.12.dll" )

# Import target "itkTestDriver" for configuration "Release"
set_property(TARGET itkTestDriver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(itkTestDriver PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/itkTestDriver.exe"
  )

list(APPEND _IMPORT_CHECK_TARGETS itkTestDriver )
list(APPEND _IMPORT_CHECK_FILES_FOR_itkTestDriver "${_IMPORT_PREFIX}/bin/itkTestDriver.exe" )

# Import target "ITKVTK" for configuration "Release"
set_property(TARGET ITKVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVTK PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKVTK-4.12.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKVTK-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKVTK )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKVTK "${_IMPORT_PREFIX}/lib/ITKVTK-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKVTK-4.12.dll" )

# Import target "ITKVideoCore" for configuration "Release"
set_property(TARGET ITKVideoCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVideoCore PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKVideoCore-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKVideoCore-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKVideoCore )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKVideoCore "${_IMPORT_PREFIX}/lib/ITKVideoCore-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKVideoCore-4.12.dll" )

# Import target "ITKVideoIO" for configuration "Release"
set_property(TARGET ITKVideoIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVideoIO PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKVideoIO-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKIOImageBase;ITKVideoCore"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKVideoIO-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKVideoIO )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKVideoIO "${_IMPORT_PREFIX}/lib/ITKVideoIO-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKVideoIO-4.12.dll" )

# Import target "ITKVtkGlue" for configuration "Release"
set_property(TARGET ITKVtkGlue APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKVtkGlue PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;ITKVTK;vtkRenderingOpenGL2;vtkCommonCore;vtksys;vtkCommonDataModel;vtkCommonMath;vtkCommonMisc;vtkCommonSystem;vtkCommonTransforms;vtkCommonExecutionModel;vtkRenderingCore;vtkCommonColor;vtkCommonComputationalGeometry;vtkFiltersCore;vtkFiltersGeneral;vtkFiltersGeometry;vtkFiltersSources;vtkglew;vtkRenderingFreeType;vtkfreetype;vtkzlib;vtkInteractionStyle;vtkFiltersExtraction;vtkFiltersStatistics;vtkImagingFourier;vtkImagingCore;vtkalglib;vtkIOImage;vtkDICOMParser;vtkmetaio;vtkjpeg;vtkpng;vtktiff;vtkImagingSources"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/ITKVtkGlue-4.12.lib"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKVtkGlue )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKVtkGlue "${_IMPORT_PREFIX}/lib/ITKVtkGlue-4.12.lib" )

# Import target "ITKWatersheds" for configuration "Release"
set_property(TARGET ITKWatersheds APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ITKWatersheds PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/lib/ITKWatersheds-4.12.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/ITKWatersheds-4.12.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS ITKWatersheds )
list(APPEND _IMPORT_CHECK_FILES_FOR_ITKWatersheds "${_IMPORT_PREFIX}/lib/ITKWatersheds-4.12.lib" "${_IMPORT_PREFIX}/bin/ITKWatersheds-4.12.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
