# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ofstd ofstd_tests oflog dcmdata i2d dcm2xml dcmconv dcmcrle dcmdrle dcmdump dcmftest dcmgpdir dump2dcm xml2dcm pdf2dcm dcm2pdf img2dcm dcm2json dcmodify dcmdata_tests dcmimgle dcmdspfn dcod2lum dconvlum dcmimage dcm2pnm dcmquant dcmscale dcmjpeg ijg8 ijg12 ijg16 dcmcjpeg dcmdjpeg dcmj2pnm dcmmkdir dcmjpls charls dcmcjpls dcmdjpls dcml2pnm dcmtls dcmnet dcmrecv dcmsend echoscu findscu getscu movescu storescp storescu termscu dcmnet_tests dcmsr cmr dsr2html dsr2xml dsrdump xml2dsr mkreport dcmsr_tests dcmdsig dcmsign dcmwlm wlmscpfs wltest dcmqrdb dcmqrscp dcmqridx dcmqrti dcmpstat dcmmkcrv dcmmklut dcmp2pgm dcmprscp dcmprscu dcmpschk dcmpsmk dcmpsprt dcmpsrcv dcmpssnd msgserv dcmrt drtdump drttest dcmrt_tests dcmiod dcmiod_tests dcmfg dcmseg dcmseg_tests dcmtract dcmpmap)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target ofstd
add_library(ofstd SHARED IMPORTED)

# Create imported target ofstd_tests
add_executable(ofstd_tests IMPORTED)

# Create imported target oflog
add_library(oflog SHARED IMPORTED)

# Create imported target dcmdata
add_library(dcmdata SHARED IMPORTED)

# Create imported target i2d
add_library(i2d SHARED IMPORTED)

# Create imported target dcm2xml
add_executable(dcm2xml IMPORTED)

# Create imported target dcmconv
add_executable(dcmconv IMPORTED)

# Create imported target dcmcrle
add_executable(dcmcrle IMPORTED)

# Create imported target dcmdrle
add_executable(dcmdrle IMPORTED)

# Create imported target dcmdump
add_executable(dcmdump IMPORTED)

# Create imported target dcmftest
add_executable(dcmftest IMPORTED)

# Create imported target dcmgpdir
add_executable(dcmgpdir IMPORTED)

# Create imported target dump2dcm
add_executable(dump2dcm IMPORTED)

# Create imported target xml2dcm
add_executable(xml2dcm IMPORTED)

# Create imported target pdf2dcm
add_executable(pdf2dcm IMPORTED)

# Create imported target dcm2pdf
add_executable(dcm2pdf IMPORTED)

# Create imported target img2dcm
add_executable(img2dcm IMPORTED)

# Create imported target dcm2json
add_executable(dcm2json IMPORTED)

# Create imported target dcmodify
add_executable(dcmodify IMPORTED)

# Create imported target dcmdata_tests
add_executable(dcmdata_tests IMPORTED)

# Create imported target dcmimgle
add_library(dcmimgle SHARED IMPORTED)

# Create imported target dcmdspfn
add_executable(dcmdspfn IMPORTED)

# Create imported target dcod2lum
add_executable(dcod2lum IMPORTED)

# Create imported target dconvlum
add_executable(dconvlum IMPORTED)

# Create imported target dcmimage
add_library(dcmimage SHARED IMPORTED)

# Create imported target dcm2pnm
add_executable(dcm2pnm IMPORTED)

# Create imported target dcmquant
add_executable(dcmquant IMPORTED)

# Create imported target dcmscale
add_executable(dcmscale IMPORTED)

# Create imported target dcmjpeg
add_library(dcmjpeg SHARED IMPORTED)

# Create imported target ijg8
add_library(ijg8 SHARED IMPORTED)

# Create imported target ijg12
add_library(ijg12 SHARED IMPORTED)

# Create imported target ijg16
add_library(ijg16 SHARED IMPORTED)

# Create imported target dcmcjpeg
add_executable(dcmcjpeg IMPORTED)

# Create imported target dcmdjpeg
add_executable(dcmdjpeg IMPORTED)

# Create imported target dcmj2pnm
add_executable(dcmj2pnm IMPORTED)

# Create imported target dcmmkdir
add_executable(dcmmkdir IMPORTED)

# Create imported target dcmjpls
add_library(dcmjpls SHARED IMPORTED)

# Create imported target charls
add_library(charls SHARED IMPORTED)

# Create imported target dcmcjpls
add_executable(dcmcjpls IMPORTED)

# Create imported target dcmdjpls
add_executable(dcmdjpls IMPORTED)

# Create imported target dcml2pnm
add_executable(dcml2pnm IMPORTED)

# Create imported target dcmtls
add_library(dcmtls SHARED IMPORTED)

# Create imported target dcmnet
add_library(dcmnet SHARED IMPORTED)

# Create imported target dcmrecv
add_executable(dcmrecv IMPORTED)

# Create imported target dcmsend
add_executable(dcmsend IMPORTED)

# Create imported target echoscu
add_executable(echoscu IMPORTED)

# Create imported target findscu
add_executable(findscu IMPORTED)

# Create imported target getscu
add_executable(getscu IMPORTED)

# Create imported target movescu
add_executable(movescu IMPORTED)

# Create imported target storescp
add_executable(storescp IMPORTED)

# Create imported target storescu
add_executable(storescu IMPORTED)

# Create imported target termscu
add_executable(termscu IMPORTED)

# Create imported target dcmnet_tests
add_executable(dcmnet_tests IMPORTED)

# Create imported target dcmsr
add_library(dcmsr SHARED IMPORTED)

# Create imported target cmr
add_library(cmr SHARED IMPORTED)

# Create imported target dsr2html
add_executable(dsr2html IMPORTED)

# Create imported target dsr2xml
add_executable(dsr2xml IMPORTED)

# Create imported target dsrdump
add_executable(dsrdump IMPORTED)

# Create imported target xml2dsr
add_executable(xml2dsr IMPORTED)

# Create imported target mkreport
add_executable(mkreport IMPORTED)

# Create imported target dcmsr_tests
add_executable(dcmsr_tests IMPORTED)

# Create imported target dcmdsig
add_library(dcmdsig SHARED IMPORTED)

# Create imported target dcmsign
add_executable(dcmsign IMPORTED)

# Create imported target dcmwlm
add_library(dcmwlm SHARED IMPORTED)

# Create imported target wlmscpfs
add_executable(wlmscpfs IMPORTED)

# Create imported target wltest
add_executable(wltest IMPORTED)

# Create imported target dcmqrdb
add_library(dcmqrdb SHARED IMPORTED)

# Create imported target dcmqrscp
add_executable(dcmqrscp IMPORTED)

# Create imported target dcmqridx
add_executable(dcmqridx IMPORTED)

# Create imported target dcmqrti
add_executable(dcmqrti IMPORTED)

# Create imported target dcmpstat
add_library(dcmpstat SHARED IMPORTED)

# Create imported target dcmmkcrv
add_executable(dcmmkcrv IMPORTED)

# Create imported target dcmmklut
add_executable(dcmmklut IMPORTED)

# Create imported target dcmp2pgm
add_executable(dcmp2pgm IMPORTED)

# Create imported target dcmprscp
add_executable(dcmprscp IMPORTED)

# Create imported target dcmprscu
add_executable(dcmprscu IMPORTED)

# Create imported target dcmpschk
add_executable(dcmpschk IMPORTED)

# Create imported target dcmpsmk
add_executable(dcmpsmk IMPORTED)

# Create imported target dcmpsprt
add_executable(dcmpsprt IMPORTED)

# Create imported target dcmpsrcv
add_executable(dcmpsrcv IMPORTED)

# Create imported target dcmpssnd
add_executable(dcmpssnd IMPORTED)

# Create imported target msgserv
add_executable(msgserv IMPORTED)

# Create imported target dcmrt
add_library(dcmrt SHARED IMPORTED)

# Create imported target drtdump
add_executable(drtdump IMPORTED)

# Create imported target drttest
add_executable(drttest IMPORTED)

# Create imported target dcmrt_tests
add_executable(dcmrt_tests IMPORTED)

# Create imported target dcmiod
add_library(dcmiod SHARED IMPORTED)

# Create imported target dcmiod_tests
add_executable(dcmiod_tests IMPORTED)

# Create imported target dcmfg
add_library(dcmfg SHARED IMPORTED)

# Create imported target dcmseg
add_library(dcmseg SHARED IMPORTED)

# Create imported target dcmseg_tests
add_executable(dcmseg_tests IMPORTED)

# Create imported target dcmtract
add_library(dcmtract SHARED IMPORTED)

# Create imported target dcmpmap
add_library(dcmpmap SHARED IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/DCMTKTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
