set(ITKConvolution_LOADED 1)
set(ITKConvolution_ENABLE_SHARED "0")
set(ITKConvolution_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PUBLIC_DEPENDS "")
set(ITKConvolution_TRANSITIVE_DEPENDS "ITKFFT;ITKImageIntensity;ITKThresholding")
set(ITKConvolution_PRIVATE_DEPENDS "")
set(ITKConvolution_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKConvolution_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKConvolution_LIBRARY_DIRS "")
set(ITKConvolution_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKConvolution_TARGETS_FILE "")

