set(ITKFastMarching_LOADED 1)
set(ITKFastMarching_ENABLE_SHARED "0")
set(ITKFastMarching_DEPENDS "ITKConnectedComponents;ITKMesh;ITKQuadEdgeMesh")
set(ITKFastMarching_PUBLIC_DEPENDS "")
set(ITKFastMarching_TRANSITIVE_DEPENDS "ITKConnectedComponents;ITKMesh;ITKQuadEdgeMesh")
set(ITKFastMarching_PRIVATE_DEPENDS "")
set(ITKFastMarching_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKMesh;ITKQuadEdgeMesh")
set(ITKFastMarching_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKFastMarching_LIBRARY_DIRS "")
set(ITKFastMarching_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKFastMarching_TARGETS_FILE "")

