set(ITKGPUSmoothing_LOADED 1)
set(ITKGPUSmoothing_ENABLE_SHARED "0")
set(ITKGPUSmoothing_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUImageFilterBase;ITKSmoothing")
set(ITKGPUSmoothing_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUImageFilterBase")
set(ITKGPUSmoothing_TRANSITIVE_DEPENDS "ITKCommon;ITKGPUCommon;ITKGPUImageFilterBase;ITKSmoothing")
set(ITKGPUSmoothing_PRIVATE_DEPENDS "")
set(ITKGPUSmoothing_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform")
set(ITKGPUSmoothing_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKGPUSmoothing_LIBRARY_DIRS "")
set(ITKGPUSmoothing_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUSmoothing_TARGETS_FILE "")

