set(ITKGPUFiniteDifference_LOADED 1)
set(ITKGPUFiniteDifference_ENABLE_SHARED "0")
set(ITKGPUFiniteDifference_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUFiniteDifference_TRANSITIVE_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PRIVATE_DEPENDS "")
set(ITKGPUFiniteDifference_LIBRARIES "ITKCommon")
set(ITKGPUFiniteDifference_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKGPUFiniteDifference_LIBRARY_DIRS "")
set(ITKGPUFiniteDifference_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKGPUFiniteDifference_TARGETS_FILE "")

