set(ITKImageGradient_LOADED 1)
set(ITKImageGradient_ENABLE_SHARED "0")
set(ITKImageGradient_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PUBLIC_DEPENDS "")
set(ITKImageGradient_TRANSITIVE_DEPENDS "ITKImageAdaptors;ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_PRIVATE_DEPENDS "")
set(ITKImageGradient_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKImageGradient_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKImageGradient_LIBRARY_DIRS "")
set(ITKImageGradient_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKImageGradient_TARGETS_FILE "")

