set(ITKLevelSetsv4_LOADED 1)
set(ITKLevelSetsv4_ENABLE_SHARED "0")
set(ITKLevelSetsv4_DEPENDS "ITKCommon;ITKDistanceMap;ITKImageGradient;ITKLabelMap")
set(ITKLevelSetsv4_PUBLIC_DEPENDS "ITKCommon;ITKDistanceMap;ITKImageGradient;ITKLabelMap")
set(ITKLevelSetsv4_TRANSITIVE_DEPENDS "ITKCommon;ITKDistanceMap;ITKImageGradient;ITKLabelMap")
set(ITKLevelSetsv4_PRIVATE_DEPENDS "")
set(ITKLevelSetsv4_LIBRARIES "ITKCommon;ITKLabelMap;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKLevelSetsv4_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKLevelSetsv4_LIBRARY_DIRS "")
set(ITKLevelSetsv4_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKLevelSetsv4_TARGETS_FILE "")

