set(ITKMathematicalMorphology_LOADED 1)
set(ITKMathematicalMorphology_ENABLE_SHARED "0")
set(ITKMathematicalMorphology_DEPENDS "ITKConnectedComponents;ITKImageFilterBase;ITKImageGrid;ITKImageIntensity;ITKThresholding")
set(ITKMathematicalMorphology_PUBLIC_DEPENDS "")
set(ITKMathematicalMorphology_TRANSITIVE_DEPENDS "ITKConnectedComponents;ITKImageFilterBase;ITKImageGrid;ITKImageIntensity;ITKThresholding")
set(ITKMathematicalMorphology_PRIVATE_DEPENDS "")
set(ITKMathematicalMorphology_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath")
set(ITKMathematicalMorphology_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKMathematicalMorphology_LIBRARY_DIRS "")
set(ITKMathematicalMorphology_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKMathematicalMorphology_TARGETS_FILE "")

