set(ITKVideoFiltering_LOADED 1)
set(ITKVideoFiltering_ENABLE_SHARED "0")
set(ITKVideoFiltering_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_PUBLIC_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_TRANSITIVE_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_PRIVATE_DEPENDS "")
set(ITKVideoFiltering_LIBRARIES "ITKVideoCore")
set(ITKVideoFiltering_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-4.12")
set(ITKVideoFiltering_LIBRARY_DIRS "")
set(ITKVideoFiltering_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/bin")
set(ITKVideoFiltering_TARGETS_FILE "")

